automation:
- id: '1628794276961'
  alias: Turn TV-Light off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: !secret govee_livingroom_tv_light_device_id
    entity_id: light.livingroom_tv_light
    domain: light
    for:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: !secret govee_livingroom_tv_light_device_id
    entity_id: light.livingroom_tv_light
    domain: light
  mode: single