# It's not possible to configure the names through the gui
timer:
  cooking_timer:
    name: Timer

automation:
- alias: 'Timer done'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.cooking_timer
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.sonos_livingroom
        volume: 0.3
        message: 'Your time is over.'
        delay: '00:00:03'

input_number:
  timer_seconds:
    initial: 0
    max: 60
    min: 0
    step: 1
  timer_minutes:
    initial: 0
    max: 60
    min: 0
    step: 1
  timer_hours:
    initial: 0
    max: 60
    min: 0
    step: 1

script:
  timer_start:
    sequence:
    - service: timer.start
      data_template:
        entity_id: timer.cooking_timer
        #duration: '00:{{ states.input_number.timer_minutes.state | int }}:{{ states.input_number.timer_seconds.state | int }}'
        duration: '{{ states.input_number.timer_hours.state | int }}:{{ states.input_number.timer_minutes.state | int }}:{{ states.input_number.timer_seconds.state | int }}'

  timer_cancel:
    sequence:
    - service: timer.cancel
      data:
        entity_id: timer.cooking_timer
