# Sonos ########################################################################
- id: sonos_livingroom_bass
  alias: Sonos Livingroom Bass
  trigger:
    - platform: state
      entity_id: input_number.sonos_livingroom_bass
  action:
    - service: shell_command.sonos_bass
      data_template:
        room: 'Wohnzimmer' # Use the name from the Sonos app
        bass: '{{ trigger.to_state.state | int }}'
- id: sonos_livingroom_treble
  alias: Sonos Livingroom Treble
  trigger:
    - platform: state
      entity_id: input_number.sonos_livingroom_treble
  action:
    - service: shell_command.sonos_treble
      data_template:
        room: 'Wohnzimmer' # Use the name from the Sonos app
        treble: '{{ trigger.to_state.state | int }}'
- id: sonos_livingroom_sub_gain
  alias: Sonos Livingroom Sub Gain
  trigger:
    - platform: state
      entity_id: input_number.sonos_livingroom_sub_gain
  action:
    - service: shell_command.sonos_sub_gain
      data_template:
        room: 'Wohnzimmer' # Use the name from the Sonos app
        sub_gain: '{{ trigger.to_state.state | int }}'
- id: sonos_livingroom_sub_crossover
  alias: Sonos Livingroom Sub Crossover
  trigger:
    - platform: state
      entity_id: input_number.sonos_livingroom_sub_crossover
  action:
    - service: shell_command.sonos_sub_crossover
      data_template:
        room: 'Wohnzimmer' # Use the name from the Sonos app
        sub_crossover: '{{ trigger.to_state.state | int }}'
################################################################################

# Timer ########################################################################
- alias: 'Timer done'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.cooking_timer
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.sonos_livingroom
        volume: 0.3
        message: 'Your time is over.'
        delay: '00:00:03'
- alias: 'Phone Status'
  trigger:
    - platform: state
      entity_id: sensor.phone
  action:
    - service: notify.notify
      data:
        title: 'Phone'
        message: >-
          {% if is_state("sensor.phone", "idle") %}
            Phone in standby
          {% elif is_state("sensor.phone", "dialing") %}
            Calling {{ state_attr('sensor.phone', 'to_name') }} ({{ state_attr('sensor.phone', 'to') }})
          {% elif is_state("sensor.phone", "ringing") %}
            Incoming call from {{ state_attr('sensor.phone', 'from_name') }} ({{ state_attr('sensor.phone', 'from') }})
          {% else %}
            Phone with {{ state_attr('sensor.phone', 'with_name') }} ({{ state_attr('sensor.phone', 'with') }})
          {% endif %}
################################################################################

# Git push #####################################################################
- id: gitpush
  alias: Push HASS configuration to GitHub
  trigger:
  - at: '02:00:00'
    platform: time
  action:
  # It's important to install the community addon “SSH & Web Terminal”, not the “official” one “Web Terminal & SSH”.
  # I had to disable SSH in the configuration and Protection Mode of this addon.
  - data:
      addon: 'a0d7b954_ssh'
      input: '/config/ha_gitpush.sh'
    service: hassio.addon_stdin
