- id: '1640522228516'
  alias: Livingroom TV on - Shutter down
  description: 'Closes the shutter to avoid reflections through the window while watching
    TV. '
  trigger:
  - platform: numeric_state
    entity_id: sensor.livingroom_tv_power_consumption
    above: '20'
  condition: []
  action:
  - device_id: e8a0c9ad01d33eee439d3e9cbf6bbbf5
    domain: cover
    entity_id: cover.livingroom_shutter_small
    type: set_position
    position: 0
  mode: single
- id: '1641237098329'
  alias: All Shutter down
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-1'
  condition: []
  action:
  - device_id: e8a0c9ad01d33eee439d3e9cbf6bbbf5
    domain: cover
    entity_id: cover.livingroom_shutter_small
    type: set_position
    position: 0
  - service: script.bedroom_shutter_favorite
    data: {}
  - service: script.office_shutter_favorite
    data: {}
  mode: single
- id: '1641237270223'
  alias: Livingroom Shutter up
  description: Open the shutter in the living room when the TV is on, after sunrise
    or at the appropriate time.
  trigger:
  - platform: time
    at: 08:00:00
  - platform: sun
    event: sunrise
    offset: '+1'
  condition:
  - condition: numeric_state
    entity_id: sensor.livingroom_tv_power_consumption
    below: '2'
    enabled: true
  action:
  - device_id: e8a0c9ad01d33eee439d3e9cbf6bbbf5
    domain: cover
    entity_id: cover.livingroom_shutter_small
    type: set_position
    position: 100
  mode: single
- id: '1642241222443'
  alias: 'HASS: Dropbox-Backup'
  description: ''
  trigger:
  - platform: time
    at: 03:00
  condition: []
  action:
  - service: hassio.backup_full
    data: {}
  - service: hassio.addon_stdin
    data:
      addon: 782428ea_dropbox-backup
      input:
        command: upload
  mode: single
- id: '1645221509073'
  alias: 'HASS: GitHub-Backup (fixme)'
  description: Pushes HASS config files to GitHub.
  trigger:
  - platform: time
    at: 02:00
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/integrations/gitpush/gitpush.sh
  mode: single
- id: '1650517762669'
  alias: 'HASS: Low battery level'
  description: Low battery level detection & notification for all battery sensors
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id: []
      actions:
      - service: notify.persistent_notification
        data:
          message: Low Battery Level
          title: Warning
      time: '18:00:00'
      threshold: 10
- id: '1652179746791'
  alias: Office Shutter up
  description: Open the shutter in the office on weekdays after sunrise or at an appropriate
    time.
  trigger:
  - platform: sun
    event: sunrise
    offset: '+1'
  condition: []
  action:
  - device_id: 39df41eba2aa553cb9c0ee9ef0e713e5
    domain: cover
    entity_id: cover.office_shutter
    type: set_position
    position: 100
  mode: single
- id: '1652424507352'
  alias: All Stop/Off @ 01:00
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - service: media_player.media_stop
    data: {}
    target:
      device_id:
      - b87286876b55c180c8dfc16316a35e7d
      - 1553b70b046b6dd8fbeba4f0e8c0aeea
      - 5e01f8a267780babcc5de58e7fcc77ac
      - 972d524e912f3936491f7e6c8adf8ded
      - 247f7122aa7a90ff13b8ba771073539e
      - 6620ecddea86dec1ea7853bc633cc8a6
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - schlafzimmer
      - wohnzimmer
      - kuche
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.kitchen_pc
      - switch.kitchen_cookerhood
      - switch.livingroom_fan
  mode: single
- id: '1652647649459'
  alias: Kitchen Cookerhood stop
  description: Automatically turns off the cooker hood after a certain time.
  trigger:
  - platform: device
    type: turned_on
    device_id: 0d509434e5813a91e01bf0330ab90f17
    entity_id: switch.kitchen_cookerhood
    domain: switch
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 0d509434e5813a91e01bf0330ab90f17
    entity_id: switch.kitchen_cookerhood
    domain: switch
  mode: single
- id: '1652896923568'
  alias: Bedroom Shutter Favorite
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '+1'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    attribute: workdays
    state: 'on'
  action:
  - device_id: cc7215817ef8193b2df878dad98cb347
    domain: cover
    entity_id: cover.bedroom_shutter
    type: set_position
    position: 40
  mode: single
- id: '1652978544840'
  alias: 'HASS: Away'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.galaxy_s9_2
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: vacuum.turn_on
    data: {}
    target:
      entity_id: vacuum.e0001103417610630506
  - service: media_player.media_stop
    data: {}
    target:
      device_id:
      - b87286876b55c180c8dfc16316a35e7d
      - 1553b70b046b6dd8fbeba4f0e8c0aeea
      - 5e01f8a267780babcc5de58e7fcc77ac
      - 972d524e912f3936491f7e6c8adf8ded
      - 247f7122aa7a90ff13b8ba771073539e
      - 6620ecddea86dec1ea7853bc633cc8a6
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bedroom_light
      - light.kitchen_light_group
      - light.livingroom_floodlight
      - light.livingroom_tv_light
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - cbf6bb49e2823487b31dfdf305e033d8
      - 1e9a16f4d3c307044b1aafaec641833b
      - 0d509434e5813a91e01bf0330ab90f17
      - 2963d98a0a5f3f18a618dbb4ff4339b5
      - 48608a926e1e91846fb7ded6dafd2b0c
  mode: single
- id: '1652986188792'
  alias: 'HASS: At Home'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.galaxy_s9_2
    from: not_home
    to: home
  condition: []
  action:
  - service: vacuum.return_to_base
    data: {}
    target:
      entity_id: vacuum.e0001103417610630506
  mode: single
- id: '1654138222259'
  alias: Corridor Headphones Stop
  description: This automation is intended to prevent the morning alarm clock from
    being accidentally overheard.
  trigger:
  - platform: time
    at: 06:55:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    attribute: workdays
    state: 'on'
  action:
  - service: media_player.media_stop
    data: {}
    target:
      device_id: 5e01f8a267780babcc5de58e7fcc77ac
  mode: single
- id: '1654140113306'
  alias: Bedroom Shutter up
  description: Open the shutter in the bedroom on weekdays at the appropriate time.
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    attribute: workdays
    state: 'on'
  action:
  - device_id: cc7215817ef8193b2df878dad98cb347
    domain: cover
    entity_id: cover.bedroom_shutter
    type: set_position
    position: 100
  mode: single
- id: '1654438759695'
  alias: Sonos Night Mode Workday (Bedroom)
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - device_id: 4c4c037e477694001454c9891259cbce
    domain: number
    entity_id: number.sonos_bedroom_bass
    type: set_value
    value: -10
  mode: single
- id: '1654439759794'
  alias: Sonos Livingroom Sub Crossover (fixme)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - automation.sonos_livingroom_sub_crossover
  condition: []
  action:
  - service: shell_command.sonos_livingroom_sub_crossover
    data_template:
      room: Livingroom
      sub_crossover: '{{ trigger.to_state.state | int }}'
  mode: single
- id: '1654695792819'
  alias: Livingroom TV off - Shutter up
  description: Opens the shutter when the TV is turned off one hour before sunset.
  trigger:
  - platform: numeric_state
    entity_id: sensor.livingroom_tv_power_consumption
    below: '2'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition:
  - condition: sun
    before: sunset
    before_offset: '-1'
  - condition: numeric_state
    entity_id: sensor.livingroom_pushbutton_temperature
    below: '23'
  action:
  - device_id: e8a0c9ad01d33eee439d3e9cbf6bbbf5
    domain: cover
    entity_id: cover.livingroom_shutter_small
    type: set_position
    position: 100
  mode: single
- id: '1654703012752'
  alias: Sonos Night Light on
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 662784da2f9ebd37eaf61933752980c3
    entity_id: switch.sonos_bathroom_status_light
    domain: switch
  - type: turn_on
    device_id: 8c64314c257f91f3e312a0595308be00
    entity_id: switch.sonos_kitchen_status_light
    domain: switch
  - type: turn_on
    device_id: ed83c0a7b5745c8f9a1b3e9aef50a991
    entity_id: switch.sonos_livingroom_status_light
    domain: switch
  - type: turn_on
    device_id: 35ca0a10f0d4ef5b5dfcbd94329f8432
    entity_id: switch.sonos_office_status_light
    domain: switch
  mode: single
- id: '1654703080922'
  alias: Sonos Night Light off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '-1'
  condition: []
  action:
  - type: turn_off
    device_id: 662784da2f9ebd37eaf61933752980c3
    entity_id: switch.sonos_bathroom_status_light
    domain: switch
  - type: turn_off
    device_id: 8c64314c257f91f3e312a0595308be00
    entity_id: switch.sonos_kitchen_status_light
    domain: switch
  - type: turn_off
    device_id: ed83c0a7b5745c8f9a1b3e9aef50a991
    entity_id: switch.sonos_livingroom_status_light
    domain: switch
  - type: turn_off
    device_id: 35ca0a10f0d4ef5b5dfcbd94329f8432
    entity_id: switch.sonos_office_status_light
    domain: switch
  - type: turn_off
    device_id: 4c4c037e477694001454c9891259cbce
    entity_id: switch.sonos_bedroom_status_light
    domain: switch
  mode: single
- id: '1655212907581'
  alias: Livingroom Sun Protection
  description: Close the shutter when the sun shines into the window and the in-/outside
    temperature is above a certain value, but only if the TV is off.
  trigger:
  - platform: numeric_state
    entity_id: sensor.livingroom_pushbutton_temperature
    above: '23'
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: '100'
    below: '250'
  - condition: numeric_state
    entity_id: sensor.livingroom_tv_power_consumption
    below: '20'
  action:
  - service: script.livingroom_shutter_favorite
    data: {}
  mode: single
- id: '1656021860713'
  alias: Bedroom Shutter Down
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - device_id: cc7215817ef8193b2df878dad98cb347
    domain: cover
    entity_id: cover.bedroom_shutter
    type: set_position
    position: 0
  mode: single
- id: '1657476087267'
  alias: Livingroom PC off - TV off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.livingroom_nuc_power_consumption
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: '9'
  condition: []
  action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.android_tv_livingroom
  mode: single
- id: '1657477115931'
  alias: Livingroom PC on - TV on
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.livingroom_nuc_power_consumption
    for:
      hours: 0
      minutes: 0
      seconds: 0
    above: '10'
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 34:93:42:22:74:92
  mode: single
- id: '1657518721213'
  alias: Office Sun Protection
  description: Close the shutter when the sun shines into the window and the in-/outside
    temperature is above a certain value.
  trigger:
  - platform: numeric_state
    entity_id: climate.office_thermostat
    above: '22'
    attribute: current_temperature
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: azimuth
    above: '70'
    below: '150'
  action:
  - service: script.office_shutter_favorite
    data: {}
  mode: single
