homeassistant:
  customize: !include customize.yaml # Customizations from Configuration > Customizations will be stored here
  packages: !include_dir_named integrations

################################################################################

frontend:
  themes: !include_dir_merge_named themes

# Includes #####################################################################
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
################################################################################

default_config: # Configure a default setup of Home Assistant (frontend, api, etc)

wake_on_lan: # Further configuration in the corresponding package yaml files

sensor:
  - platform: template
    sensors:
      basement_washer_on:
        value_template: >
          {% if states.sensor.basement_washer_power_consumption.state | float > 4 %}
            On
          {% else %}
            Off
          {% endif %}
      bedroom_current_temperature:
        value_template: "{{ state_attr('climate.bedroom_thermostat', 'current_temperature') }}"
        unit_of_measurement: "°C"
      kitchen_dishwasher_on:
        value_template: >
          {% if states.sensor.kitchen_dishwasher_power_consumption.state | float > 2 %}
            On
          {% else %}
            Off
          {% endif %}
      office_current_temperature:
        value_template: "{{ state_attr('climate.office_thermostat', 'current_temperature') }}"
        unit_of_measurement: "°C"
      storeroom_akku_charged:
        value_template:  >
          {% if states.sensor.storeroom_switch_power_consumption.state | float > 1 %}
            Charging
          {% else %}
            100%
          {% endif %}
      electricity_price:
        value_template: "0.298"
# Weather
      humidity_outside:
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.home', 'humidity') }}"
      pressure_outside:
        unit_of_measurement: 'hPa'
        value_template: "{{ state_attr('weather.home', 'pressure') }}"
      temperature_outside:
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
      wind_speed_outside:
        unit_of_measurement: 'km/h'
        value_template: "{{ state_attr('weather.home', 'wind_speed') }}"
