homeassistant:
  customize: !include customize.yaml # Customizations from Configuration > Customizations will be stored here
  packages: !include_dir_named integrations

 # Experiment
  allowlist_external_dirs:
    - "/"
################################################################################

# Got the following error message, but it has since disappeared:
# Config entry 'FRITZ!Box 7490' for fritzbox integration not ready yet: invalid literal for int() with base 10: ''; Retrying in background
#logger:
#  default: info
#  logs:
#    homeassistant.components.fritzbox: debug

frontend:
  themes: !include_dir_merge_named themes

# Lovelace #####################################################################
#
# Since I configure lovelace via the graphical interface,
# this section is only for demonstration purposes
# and in case you run Home Assistant in yaml mode.
# I have copied the raw code from the editor manually to <config>/ui-lovelace.yaml
#
# Take a look here for more information:
# https://www.home-assistant.io/lovelace/dashboards-and-views/
#
#lovelace:
#  mode: yaml
#  resources:
     # Toggle fullscreen
#    - url: /hacsfiles/fullscreen-card/fullscreen-card.js
#      type: module
     # Kiosk mode - not tested yet
#    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
#      type: module
#    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
#      type: module
#    - url: /hacsfiles/lovelace-card-mod/card-mod.js
#      type: module
#    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js?hacstag=1507819942004
#      type: module
#    - url: /hacsfiles/lovelace-layout-card/layout-card.js
#      type: module
#    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js?hacstag=1448997001710
#      type: module
     # Vacuum card not only for Xiaomi products
#    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
#      type: module
     # Very configurable media player
#    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
#      type: module
     # Custom thermostat
#    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
#      type: module
     # Nice timer bar for my timer
#    - url: /hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=37690451712
#      type: module
#    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
#      type: module
################################################################################

# Includes #####################################################################
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
################################################################################

default_config: # Configure a default setup of Home Assistant (frontend, api, etc)

tts: # Text to speech
  - platform: google_translate
    language: 'en'

# Experiment
folder_watcher:
  - folder: /

wake_on_lan: # Further configuration in the corresponding package yaml files

sensor:
  - platform: time_date # Nescessary for the timer
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: uptime # The uptime sensor stores the timestamp (date and time) when Home Assistant was last started.
  - platform: template
    sensors:
      date:
        entity_id: sensor.time
        value_template: "{{ as_timestamp(now()) | timestamp_custom('%A, %d.%m.%Y') }}"
      time_formatted:
        value_template: "{{ as_timestamp(states('sensor.date_time_utc')) | timestamp_custom('%A %B %-m, %I:%M %p') }}"
      basement_washer_on:
        friendly_name: 'Washer on'
        value_template: "{{ states('sensor.basement_washer_power_consumption') | float > 5 }}"
      basement_dishwasher_on:
        friendly_name: 'Dishwasher on'
        value_template: "{{ states('sensor.basement_dishwasher_power_consumption') | float > 5 }}"
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: "/"
    # ToDo ##########################
    - type: disk_use_percent
      arg: "/dev/sda" # /mnt/Music
    - type: disk_use_percent
      arg: "/dev/sdc1" # /mnt/Backups
    - type: disk_use_percent
      arg: "/dev/sdb1" # /mnt/External
    ##################################
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    # ToDo ###########################
    - type: network_in
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    # ToDo
    - type: processor_temperature
    - type: processor_use
    - type: swap_use_percent

# ToDo
  #- platform: wake_on_lan
    #mac: !secret rock_mac
