homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

 # Experiment
  allowlist_external_dirs:
    - "/mnt"
################################################################################

frontend:
  themes: !include_dir_merge_named themes

# Includes #####################################################################
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
################################################################################

default_config: # Configure a default setup of Home Assistant (frontend, api, etc)

tts: # Text to speech
  - platform: google_translate
    language: 'en'

# Experiment
folder_watcher:
  - folder: /mnt

wake_on_lan: # Further configuration in the corresponding package yaml files

sensor:
  - platform: command_line
    name: NUC CPU Temperature # It's not possible to configure the name through the UI
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
  - platform: time_date # Nescessary for the timer
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: uptime # The uptime sensor stores the timestamp (date and time) when Home Assistant was last started.
  - platform: template
    sensors:
      date:
        entity_id: sensor.time
        value_template: "{{ as_timestamp(now()) | timestamp_custom('%A, %d.%m.%Y') }}"
      time_formatted:
        friendly_name: "Date and time"
        value_template: "{{ as_timestamp(states('sensor.date_time_utc')) | timestamp_custom('%A %B %-m, %I:%M %p') }}"

# ToDo
  #- platform: wake_on_lan
    #mac: !secret rock_mac
