homeassistant:
  #customize: !include customize.yaml # Customizations from Configuration > Customizations will be stored here
  packages: !include_dir_named integrations

################################################################################

frontend:
  themes: !include_dir_merge_named themes

# Includes #####################################################################
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
################################################################################

default_config: # Configure a default setup of Home Assistant (frontend, api, etc)

wake_on_lan: # Further configuration in the corresponding package yaml files

binary_sensor:
  - platform: workday
    country: DE
    province: BY

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'

template:
  - binary_sensor:
      - name: "Basement Washer on"
        unique_id: "basement_washer_on"
        state: >
          {% if states.sensor.basement_washer_power_consumption.state | float > 2 %}
            on
          {% else %}
            off
          {% endif %}
      - name: "Kitchen Dishwasher on"
        unique_id: "kitchen_dishwasher_on"
        state: >
          {% if states.sensor.kitchen_dishwasher_power_consumption.state | float > 2 %}
            on
          {% else %}
            off
          {% endif %}

      - name: "Livingroom NUC on"
        unique_id: "livingroom_nuc_on"
        state: >
          {% if states.sensor.livingroom_nuc_power_consumption.state | float > 2 %}
            on
          {% else %}
            off
          {% endif %}

      - name: "Makita Akku charged"
        unique_id: "makita_akku_charged"
        state:  >
          {% if states.sensor.storeroom_switch_power_consumption.state | float > 1 %}
            charging
          {% else %}
            100
          {% endif %}
  - sensor:
      - name: "Electricity Price"
        unique_id: "electricity_price"
        # 2022-06-07
        state: "0.309"
