homeassistant:
  customize: !include customize.yaml # Customizations from Configuration > Customizations will be stored here
  packages: !include_dir_named packages

 # Experiment
  allowlist_external_dirs:
    - "/mnt"
################################################################################

# Got the following error message, but it has since disappeared:
# Config entry 'FRITZ!Box 7490' for fritzbox integration not ready yet: invalid literal for int() with base 10: ''; Retrying in background
#logger:
#  default: info
#  logs:
#    homeassistant.components.fritzbox: debug

frontend:
  themes: !include_dir_merge_named themes

# Lovelace #####################################################################
#
# Since I configure lovelace via the graphical interface,
# this section is only for demonstration purposes
# and in case you run Home Assistant in yaml mode.
# I have copied the raw code from the editor manually to <config>/ui-lovelace.yaml
#
# Take a look here for more information:
# https://www.home-assistant.io/lovelace/dashboards-and-views/
#
#lovelace:
#  mode: yaml
#  resources:
     # Toggle fullscreen
#    - url: /hacsfiles/fullscreen-card/fullscreen-card.js
#      type: module
     # Kiosk mode - not tested yet
#    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
#      type: module
#    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
#      type: module
#    - url: /hacsfiles/lovelace-card-mod/card-mod.js
#      type: module
#    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js?hacstag=1507819942004
#      type: module
#    - url: /hacsfiles/lovelace-layout-card/layout-card.js
#      type: module
#    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js?hacstag=1448997001710
#      type: module
     # Vacuum card not only for Xiaomi products
#    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
#      type: module
     # Very configurable media player
#    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
#      type: module
     # Custom thermostat
#    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
#      type: module
     # Nice timer bar for my timer
#    - url: /hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=37690451712
#      type: module
#    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
#      type: module
################################################################################

# Includes #####################################################################
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
################################################################################

default_config: # Configure a default setup of Home Assistant (frontend, api, etc)

tts: # Text to speech
  - platform: google_translate
    language: 'en'

# Experiment
folder_watcher:
  - folder: /mnt

wake_on_lan: # Further configuration in the corresponding package yaml files

sensor:
  - platform: command_line
    name: NUC CPU Temperature # Entity is not recognized without this line.
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
  - platform: time_date # Nescessary for the timer
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: uptime # The uptime sensor stores the timestamp (date and time) when Home Assistant was last started.
  - platform: template
    sensors:
      date:
        entity_id: sensor.time
        value_template: "{{ as_timestamp(now()) | timestamp_custom('%A, %d.%m.%Y') }}"
      time_formatted:
        value_template: "{{ as_timestamp(states('sensor.date_time_utc')) | timestamp_custom('%A %B %-m, %I:%M %p') }}"

# ToDo
  #- platform: wake_on_lan
    #mac: !secret rock_mac
