title: Home
views:
  - theme: Caule Black Blue
    title: Home
    icon: mdi:home
    badges:
      - entity: sensor.sm_g960f_battery_level
      - entity: sensor.lenovo_tab_2_a10_70f_akkufullstand
      - entity: sensor.storeroom_akku_charged
      - entity: sensor.kitchen_dishwasher_on
      - entity: sensor.basement_washer_on
      - entity: switch.heatingroom_pump
      - entity: binary_sensor.livingroom_balcony_door
    cards:
      - type: entities
        entities:
          - entity: weather.home
          - entity: media_player.roon_headphones
            type: custom:mini-media-player
            artwork: full-cover-fit
            group: true
            idle_view:
              when_paused: true
            hide:
              mute: true
              power: true
              progress: true
              volume: true
        show_header_toggle: false
        state_color: true
      - type: entities
        entities:
          - entity: climate.livingroom_thermostat
            name: Livingroom
          - entity: sensor.livingroom_pushbutton_humidity
            name: Humidity
          - entity: sensor.sm_g960f_pressure_sensor
            name: Pressure
          - entity: media_player.roon_livingroom
            type: custom:mini-media-player
            group: true
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              source: true
              volume_level: false
            speaker_group:
              platform: media_player
              show_group_count: true
              supports_master: false
              entities:
                - entity_id: media_player.roon_livingroom
                  name: Livingroom
                - entity_id: media_player.roon_office
                  name: Office
                - entity_id: media_player.roon_kitchen
                  name: Kitchen
                - entity_id: media_player.roon_bathroom
                  name: Bathroom
                - entity_id: media_player.roon_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_livingroom_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_livingroom_treble
            name: Treble
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_livingroom_sub_gain
            name: Sub Gain
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_livingroom_sub_crossover
            name: Sub Crossover
        header:
          type: buttons
          entities:
            - light.livingroom_floodlight
            - switch.livingroom_tv_power
            - light.livingroom_tv_light
            - vacuum.e0001103417610630506
            - switch.livingroom_fan
            - cover.livingroom_shutter_small
        footer:
          type: buttons
          entities:
            - switch.sonos_livingroom_speech_enhancement
            - switch.sonos_livingroom_night_sound
            - switch.sonos_livingroom_surround_enabled
            - switch.sonos_livingroom_subwoofer_enabled
            - switch.sonos_livingroom_sub_polarity
            - switch.sonos_livingroom_touch_controls
            - switch.sonos_livingroom_status_light
            - sensor.livingroom_audio_input_format
        show_header_toggle: false
        state_color: true
      - type: entities
        entities:
          - entity: climate.office_thermostat
            name: Office
          - entity: media_player.roon_office
            type: custom:mini-media-player
            artwork: full-cover-fit
            group: true
            idle_view:
              when_paused: true
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: media_player
              show_group_count: true
              supports_master: false
              entities:
                - entity_id: media_player.roon_livingroom
                  name: Livingroom
                - entity_id: media_player.roon_office
                  name: Office
                - entity_id: media_player.roon_kitchen
                  name: Kitchen
                - entity_id: media_player.roon_bathroom
                  name: Bathroom
                - entity_id: media_player.roon_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_office_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_office_treble
            name: Treble
        show_header_toggle: false
        footer:
          type: buttons
          entities:
            - switch.sonos_office_touch_controls
            - switch.sonos_office_status_light
            - binary_sensor.sonos_office_microphone
        state_color: true
        header:
          type: buttons
          entities:
            - camera.office
      - type: entities
        entities:
          - entity: sensor.kitchen_cookerhood_temperature
            name: Kitchen
          - entity: media_player.roon_kitchen
            type: custom:mini-media-player
            artwork: full-cover-fit
            group: true
            idle_view:
              when_paused: true
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: media_player
              show_group_count: true
              supports_master: false
              entities:
                - entity_id: media_player.roon_livingroom
                  name: Livingroom
                - entity_id: media_player.roon_office
                  name: Office
                - entity_id: media_player.roon_kitchen
                  name: Kitchen
                - entity_id: media_player.roon_bathroom
                  name: Bathroom
                - entity_id: media_player.roon_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_kitchen_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_kitchen_treble
            name: Treble
        header:
          type: buttons
          entities:
            - light.kitchen_mood_light
            - switch.kitchen_light
            - switch.kitchen_cookerhood
        show_header_toggle: false
        state_color: true
        footer:
          type: buttons
          entities:
            - switch.sonos_kitchen_touch_controls
            - switch.sonos_kitchen_status_light
      - type: entities
        entities:
          - entity: climate.bedroom_thermostat
            name: Bedroom
          - entity: media_player.roon_bedroom
            type: custom:mini-media-player
            group: true
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: media_player
              show_group_count: true
              supports_master: false
              entities:
                - entity_id: media_player.roon_livingroom
                  name: Livingroom
                - entity_id: media_player.roon_office
                  name: Office
                - entity_id: media_player.roon_kitchen
                  name: Kitchen
                - entity_id: media_player.roon_bathroom
                  name: Bathroom
                - entity_id: media_player.roon_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_bedroom_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_bedroom_treble
            name: Treble
        header:
          type: buttons
          entities:
            - light.bedroom_light
            - switch.adaptive_lighting_adapt_brightness_adaptive_lighting
        footer:
          type: buttons
          entities:
            - switch.sonos_bedroom_night_sound
            - switch.sonos_bedroom_speech_enhancement
            - switch.sonos_bedroom_surround_enabled
            - switch.sonos_bedroom_touch_controls
            - switch.sonos_bedroom_status_light
            - sensor.bedroom_audio_input_format
      - type: entities
        entities:
          - entity: climate.bathroom_thermostat
            name: Bathroom
          - entity: sensor.bathroom_pushbutton_humidity
            name: Humidity
          - entity: media_player.roon_bathroom
            type: custom:mini-media-player
            volume_stateless: true
            volume_step: 1
            group: true
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: media_player
              show_group_count: true
              supports_master: false
              entities:
                - entity_id: media_player.roon_livingroom
                  name: Livingroom
                - entity_id: media_player.roon_office
                  name: Office
                - entity_id: media_player.roon_kitchen
                  name: Kitchen
                - entity_id: media_player.roon_bathroom
                  name: Bathroom
                - entity_id: media_player.roon_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_bathroom_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_bathroom_treble
            name: Treble
        footer:
          type: buttons
          entities:
            - switch.sonos_bathroom_touch_controls
            - switch.sonos_bathroom_status_light
      - type: entities
        entities:
          - entity: sensor.fritz_box_7490_max_connection_download_throughput
            name: Download
          - entity: sensor.fritz_box_7490_max_connection_upload_throughput
            name: Upload
        header:
          type: buttons
          entities:
            - entity: binary_sensor.fritz_box_7490_connection
            - entity: switch.fritz_box_7490_wi_fi_fritz_nomap
            - entity: switch.fritz_box_7490_wi_fi_fritz_nomap_5ghz
            - entity: switch.fritz_box_7490_wi_fi_fnet
            - entity: binary_sensor.fritz_box_7490_firmware_update
        footer:
          type: graph
          entity: sensor.fritz_box_7490_download_throughput
          detail: 2
          hours_to_show: 1
  - icon: mdi:clock
    title: Scheduler
    badges: []
    cards:
      - type: custom:scheduler-card
        title: true
        include:
          - light
          - media_player.roon_bathroom
          - media_player.roon_bedroom
          - media_player.roon_headphones
          - media_player.roon_kitchen
          - media_player.roon_livingroom
          - media_player.roon_office
          - switch.livingroom_fan
        discover_existing: false
      - type: custom:scheduler-card
        discover_existing: false
        include:
          - climate.bathroom_thermostat
          - climate.bedroom_thermostat
          - climate.office_thermostat
          - switch
          - switch.heatingroom_switch
        title: Seasonal
      - type: custom:scheduler-card
        include:
          - input_number
        title: Sound
      - type: custom:scheduler-card
        include:
          - automation
          - script
          - switch
        exclude: []
