title: Home
views:
  - title: Home
    icon: mdi:home
    badges:
      - entity: sensor.sm_g960f_battery_level
        name: Handy
      - entity: sensor.lenovo_tab_2_a10_70f_akkufullstand
        name: Tablet
      - entity: sensor.storeroom_akku_charged
        name: Akku
      - entity: sensor.kitchen_dishwasher_on
        name: Dish
      - entity: sensor.basement_washer_on
        name: Washer
      - entity: switch.heatingroom_pump
        name: Pump
      - entity: binary_sensor.livingroom_balcony_door
        name: Balcony
    cards:
      - type: entities
        entities:
          - entity: weather.home
          - entity: media_player.roon_headphones
            type: custom:mini-media-player
            group: true
            hide:
              mute: true
              power: true
              progress: true
              volume: true
        show_header_toggle: false
        state_color: true
      - type: entities
        entities:
          - entity: climate.livingroom_thermostat
            name: Livingroom
          - entity: sensor.livingroom_pushbutton_humidity
            name: Humidity
          - entity: sensor.sm_g960f_pressure_sensor
            name: Pressure
          - entity: media_player.roon_livingroom
            type: custom:mini-media-player
            group: true
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              source: true
              volume_level: false
            speaker_group:
              platform: sonos
              show_group_count: true
              group_mgmt_entity: media_player.sonos_livingroom
              entities:
                - entity_id: media_player.sonos_livingroom
                  name: Livingroom
                - entity_id: media_player.sonos_office
                  name: Office
                - entity_id: media_player.sonos_kitchen
                  name: Kitchen
                - entity_id: media_player.sonos_bathroom
                  name: Bathroom
                - entity_id: media_player.sonos_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_livingroom_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_livingroom_treble
            name: Treble
          - entity: sensor.livingroom_audio_input_format
            name: Input Format
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_livingroom_sub_gain
            name: Sub Gain
          - type: custom:numberbox-card
            delay: 0
            entity: input_number.sonos_livingroom_sub_crossover
            name: Sub Crossover
          - type: custom:numberbox-card
            entity: number.sonos_livingroom_audio_delay
            name: Audio Delay
        header:
          type: buttons
          entities:
            - light.livingroom_floodlight
            - switch.livingroom_tv_power
            - light.livingroom_tv_light
            - vacuum.e0001103417610630506
            - switch.livingroom_fan
            - cover.livingroom_shutter_small
        footer:
          type: buttons
          entities:
            - switch.sonos_livingroom_speech_enhancement
            - switch.sonos_livingroom_night_sound
            - switch.sonos_livingroom_surround_enabled
            - switch.sonos_livingroom_subwoofer_enabled
            - switch.sonos_livingroom_sub_polarity
            - switch.sonos_livingroom_touch_controls
            - switch.sonos_livingroom_status_light
        show_header_toggle: false
        state_color: true
      - camera_view: live
        type: picture-glance
        image: https://demo.home-assistant.io/stub_config/kitchen.png
        entities:
          - entity: switch.office_camera_infrared_light
          - entity: switch.office_camera_light
        camera_image: camera.office
      - type: entities
        entities:
          - entity: climate.office_thermostat
            name: Office
          - entity: media_player.roon_office
            type: custom:mini-media-player
            group: true
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: sonos
              show_group_count: true
              group_mgmt_entity: media_player.sonos_office
              entities:
                - entity_id: media_player.sonos_livingroom
                  name: Livingroom
                - entity_id: media_player.sonos_office
                  name: Office
                - entity_id: media_player.sonos_kitchen
                  name: Kitchen
                - entity_id: media_player.sonos_bathroom
                  name: Bathroom
                - entity_id: media_player.sonos_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_office_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_office_treble
            name: Treble
        show_header_toggle: false
        footer:
          type: buttons
          entities:
            - switch.sonos_office_touch_controls
            - switch.sonos_office_status_light
            - binary_sensor.sonos_office_microphone
        state_color: true
        header:
          type: buttons
          entities:
            - camera.office
      - type: entities
        entities:
          - entity: sensor.kitchen_cookerhood_temperature
            name: Kitchen
          - entity: media_player.roon_kitchen
            type: custom:mini-media-player
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: sonos
              show_group_count: true
              group_mgmt_entity: media_player.sonos_kitchen
              entities:
                - entity_id: media_player.sonos_livingroom
                  name: Livingroom
                - entity_id: media_player.sonos_office
                  name: Office
                - entity_id: media_player.sonos_kitchen
                  name: Kitchen
                - entity_id: media_player.sonos_bathroom
                  name: Bathroom
                - entity_id: media_player.sonos_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_kitchen_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_kitchen_treble
            name: Treble
        header:
          type: buttons
          entities:
            - light.kitchen_mood_light
            - switch.kitchen_light
            - switch.kitchen_cookerhood
            - switch.kitchen_pc
        show_header_toggle: false
        state_color: true
        footer:
          type: buttons
          entities:
            - switch.sonos_kitchen_touch_controls
            - switch.sonos_kitchen_status_light
      - type: entities
        entities:
          - entity: climate.bedroom_thermostat
            name: Bedroom
          - entity: media_player.roon_bedroom
            type: custom:mini-media-player
            group: true
            volume_stateless: true
            volume_step: 1
            hide:
              mute: true
              name: true
              power: true
              progress: true
              source: true
              volume_level: false
            speaker_group:
              platform: sonos
              show_group_count: true
              group_mgmt_entity: media_player.sonos_bedroom
              entities:
                - entity_id: media_player.sonos_livingroom
                  name: Livingroom
                - entity_id: media_player.sonos_office
                  name: Office
                - entity_id: media_player.sonos_kitchen
                  name: Kitchen
                - entity_id: media_player.sonos_bathroom
                  name: Bathroom
                - entity_id: media_player.sonos_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_bedroom_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_bedroom_treble
            name: Treble
          - type: custom:numberbox-card
            entity: number.sonos_bedroom_audio_delay
            name: Audio Delay
        header:
          type: buttons
          entities:
            - light.bedroom_light
            - switch.adaptive_lighting_adapt_brightness_adaptive_lighting
        footer:
          type: buttons
          entities:
            - switch.sonos_bedroom_night_sound
            - switch.sonos_bedroom_speech_enhancement
            - switch.sonos_bedroom_surround_enabled
            - switch.sonos_bedroom_touch_controls
            - switch.sonos_bedroom_status_light
            - sensor.bedroom_audio_input_format
      - type: entities
        entities:
          - entity: climate.bathroom_thermostat
            name: Bathroom
          - entity: sensor.bathroom_pushbutton_humidity
            name: Humidity
          - entity: media_player.roon_bathroom
            type: custom:mini-media-player
            volume_stateless: true
            volume_step: 1
            group: true
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: sonos
              show_group_count: true
              group_mgmt_entity: media_player.sonos_bathroom
              entities:
                - entity_id: media_player.sonos_livingroom
                  name: Livingroom
                - entity_id: media_player.sonos_office
                  name: Office
                - entity_id: media_player.sonos_kitchen
                  name: Kitchen
                - entity_id: media_player.sonos_bathroom
                  name: Bathroom
                - entity_id: media_player.sonos_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_bathroom_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_bathroom_treble
            name: Treble
        footer:
          type: buttons
          entities:
            - switch.sonos_bathroom_touch_controls
            - switch.sonos_bathroom_status_light
  - title: Kitchen
    path: kitchen
    theme: Caule Black Blue
    icon: phu:rooms-kitchen
    badges:
      - entity: sensor.kitchen_dishwasher_on
        name: Dish
      - entity: sensor.kitchen_cookerhood_temperature
        name: Temp
    cards:
      - square: true
        columns: 4
        type: grid
        cards:
          - type: button
            tap_action:
              action: toggle
            entity: light.kitchen_mood_light
            show_name: false
            show_state: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.kitchen_light
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.kitchen_cookerhood
            show_name: false
          - show_name: false
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: switch.kitchen_pc
      - type: entities
        entities:
          - entity: media_player.roon_kitchen
            type: custom:mini-media-player
            volume_stateless: true
            volume_step: 1
            artwork: full-cover-fit
            hide:
              mute: true
              name: true
              power: true
              progress: true
              volume_level: false
            speaker_group:
              platform: sonos
              show_group_count: true
              group_mgmt_entity: media_player.sonos_kitchen
              entities:
                - entity_id: media_player.sonos_livingroom
                  name: Livingroom
                - entity_id: media_player.sonos_office
                  name: Office
                - entity_id: media_player.sonos_kitchen
                  name: Kitchen
                - entity_id: media_player.sonos_bathroom
                  name: Bathroom
                - entity_id: media_player.sonos_bedroom
                  name: Bedroom
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_kitchen_bass
            name: Bass
          - type: custom:numberbox-card
            delay: 0
            entity: number.sonos_kitchen_treble
            name: Treble
      - type: shopping-list
  - icon: mdi:clock
    title: Scheduler
    badges: []
    cards:
      - type: custom:scheduler-card
        title: true
        include:
          - light
          - media_player.roon_bathroom
          - media_player.roon_bedroom
          - media_player.roon_headphones
          - media_player.roon_kitchen
          - media_player.roon_livingroom
          - media_player.roon_office
          - switch.livingroom_fan
        discover_existing: false
      - type: custom:scheduler-card
        discover_existing: false
        include:
          - climate.bathroom_thermostat
          - climate.bedroom_thermostat
          - climate.office_thermostat
          - switch
          - switch.heatingroom_switch
        title: Seasonal
      - type: custom:scheduler-card
        include:
          - input_number
        title: Sound
      - type: custom:scheduler-card
        include:
          - automation
          - script
          - switch
        exclude: []
  - title: Wartung
    path: wartung
    theme: Caule Black Blue
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.fritz_box_7490_max_connection_download_throughput
            name: Download
          - entity: sensor.fritz_box_7490_max_connection_upload_throughput
            name: Upload
          - entity: sensor.fritz_box_7490_download_throughput
          - entity: sensor.fritz_box_7490_upload_throughput
        header:
          type: buttons
          entities:
            - entity: binary_sensor.fritz_box_7490_connection
            - entity: switch.fritz_box_7490_wi_fi_fritz_nomap
            - entity: switch.fritz_box_7490_wi_fi_fritz_nomap_5ghz
            - entity: switch.fritz_box_7490_wi_fi_fnet
            - entity: binary_sensor.fritz_box_7490_firmware_update
        footer:
          type: graph
          entity: sensor.fritz_box_7490_download_throughput
          detail: 2
          hours_to_show: 1
      - type: sensor
        entity: sensor.corridor_rock_power_consumption
        graph: line
        hours_to_show: 1
        detail: 2
      - type: sensor
        entity: sensor.corridor_rock_temperature
        graph: line
        hours_to_show: 1
        detail: 2
