media_art_background:
  width: 100%
  entities:
    - entity: media_player.roon_livingroom
      valid_states:
        - playing
      views:
        - music
title: Home
views:
  - title: Dash
    path: dash
    theme: Caule Black Blue Glass
    icon: mdi:home
    badges:
      - entity: weather.home
      - entity: sensor.fritz_box_7490_max_kbit_s_received
      - entity: sensor.sm_g960f_battery_level
      - entity: sensor.lenovo_tab_2_a10_70f_akkufullstand
      - entity: sensor.storeroom_akku_charged
      - entity: sensor.basement_washer_on
      - entity: sensor.kitchen_dishwasher_on
      - entity: switch.heatingroom_pump
    cards:
      - type: grid
        cards:
          - type: custom:mini-media-player
            entity: media_player.roon_livingroom
            toggle_power: true
            volume_stateless: true
            group: false
            hide:
              info: true
              icon: true
              mute: true
              power: true
              progress: true
              volume_level: false
            volume_step: '1'
            artwork: full-cover-fit
          - type: gauge
            entity: input_number.sonos_livingroom_bass
            max: 10
            min: -10
            name: Bass
            needle: true
          - type: gauge
            entity: input_number.sonos_livingroom_treble
            max: 10
            min: -10
            name: Treble
            needle: true
          - type: thermostat
            entity: climate.livingroom_thermostat
            name: ' '
          - type: gauge
            entity: sensor.livingroom_pushbutton_humidity
            min: 0
            max: 100
            name: ' Humidity'
            severity:
              green: 40
              yellow: 39
              red: 60
          - type: button
            tap_action:
              action: more-info
            entity: binary_sensor.livingroom_balcony_door
            show_name: false
          - type: light
            entity: light.livingroom_floodlight
            name: ' '
          - type: button
            tap_action:
              action: toggle
            entity: switch.livingroom_tv_power
            show_name: false
            show_state: false
          - type: light
            entity: light.livingroom_tv_light
            name: ' '
          - type: button
            tap_action:
              action: toggle
            entity: vacuum.e0001103417610630506
            show_state: false
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.livingroom_fan
            show_name: false
          - type: button
            tap_action:
              action: more-info
            entity: binary_sensor.livingroom_shutter_small
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_livingroom_sub
            name: Sub
            show_name: true
            icon: phu:sonos-sub
          - type: gauge
            entity: input_number.sonos_livingroom_sub_gain
            max: 15
            min: -15
            name: Gain
            needle: true
          - type: gauge
            entity: input_number.sonos_livingroom_sub_crossover
            min: 50
            max: 110
            name: Crossover
            needle: true
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_livingroom_night_sound
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_livingroom_speech_enhancement
            show_state: false
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_livingroom_buttons_enabled
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_livingroom_sub_polarity
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_livingroom_surround_enabled
            show_name: false
          - type: custom:cover-icon-element
            entities:
              - entity: binary_sensor.livingroom_shutter_small
        square: true
      - type: grid
        cards:
          - type: custom:mini-media-player
            entity: media_player.roon_headphones
            toggle_power: true
            volume_stateless: true
            group: false
            hide:
              info: true
              icon: true
              power: true
              progress: true
            volume_step: '1'
            artwork: full-cover-fit
          - type: sensor
            entity: sensor.corridor_rock_power_consumption
            graph: line
            name: ' '
          - type: sensor
            entity: sensor.corridor_rock_temperature
            graph: line
            name: ' '
      - type: grid
        cards:
          - type: custom:mini-media-player
            entity: media_player.roon_kitchen
            toggle_power: true
            volume_stateless: true
            group: false
            hide:
              info: true
              icon: true
              mute: true
              power: true
              progress: true
              volume_level: false
            volume_step: '1'
            artwork: full-cover-fit
          - type: gauge
            entity: input_number.sonos_kitchen_bass
            max: 10
            name: Bass
            min: -10
            needle: true
          - type: gauge
            entity: input_number.sonos_kitchen_treble
            max: 10
            name: Treble
            min: -10
            needle: true
          - type: button
            tap_action:
              action: toggle
            entity: switch.kitchen_cookerhood
            name: ' '
            show_name: false
            show_state: false
            icon: mdi:stove
          - type: button
            tap_action:
              action: toggle
            entity: switch.kitchen_light
            name: ' '
            show_name: false
          - type: light
            entity: light.kitchen_mood_light
            name: ' '
      - type: grid
        cards:
          - type: custom:mini-media-player
            entity: media_player.roon_office
            toggle_power: true
            volume_stateless: true
            group: false
            hide:
              info: true
              icon: true
              mute: true
              power: true
              progress: true
              volume_level: false
            volume_step: '1'
            artwork: full-cover-fit
          - type: gauge
            entity: input_number.sonos_office_bass
            max: 10
            min: -10
            needle: true
            name: Bass
          - type: gauge
            entity: input_number.sonos_office_treble
            max: 10
            min: -10
            needle: true
            name: Treble
          - type: picture-glance
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities:
              - sensor.time
              - sensor.date
            camera_image: camera.office
          - type: thermostat
            entity: climate.office_thermostat
            name: ' '
          - type: sensor
            entity: sensor.office_switch_power_consumption
            graph: line
            name: ' '
            detail: 1
            hours_to_show: 1
      - type: grid
        cards:
          - type: custom:mini-media-player
            entity: media_player.roon_bathroom
            toggle_power: true
            volume_stateless: true
            group: false
            hide:
              info: true
              icon: true
              mute: true
              power: true
              progress: true
              volume_level: false
            volume_step: '1'
            artwork: full-cover-fit
          - type: thermostat
            entity: climate.bathroom_thermostat
            name: ' '
          - type: gauge
            entity: sensor.bathroom_pushbutton_humidity
            min: 0
            max: 100
            name: Humidity
            severity:
              green: 40
              yellow: 39
              red: 60
      - type: grid
        cards:
          - type: custom:mini-media-player
            entity: media_player.roon_bedroom
            toggle_power: true
            volume_stateless: true
            group: false
            hide:
              info: true
              icon: true
              mute: true
              power: true
              progress: true
              volume_level: false
            volume_step: '1'
            artwork: full-cover-fit
          - type: light
            entity: light.bedroom_light
            name: ' '
          - type: thermostat
            entity: climate.bedroom_thermostat
            name: ' '
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_bedroom_night_sound
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_bedroom_speech_enhance
            show_name: false
          - type: button
            tap_action:
              action: toggle
            entity: switch.sonos_bedroom_buttons_enabled
            show_name: false
  - icon: mdi:clock
    title: Scheduler
    badges: []
    cards:
      - type: custom:scheduler-card
        title: true
        include:
          - light
          - media_player.roon_bathroom
          - media_player.roon_bedroom
          - media_player.roon_headphones
          - media_player.roon_kitchen
          - media_player.roon_livingroom
          - media_player.roon_office
          - switch.livingroom_fan
        discover_existing: false
      - type: custom:scheduler-card
        discover_existing: false
        include:
          - climate.bathroom_thermostat
          - climate.bedroom_thermostat
          - climate.office_thermostat
          - switch
          - switch.heatingroom_switch
        title: Seasonal
      - type: custom:scheduler-card
        include:
          - input_number
        title: Sound
