sensor:
  - platform: fritzbox_netmonitor # Monitors the network statistics exposed by AVM FRITZ!Box routers.
  - platform: template
    sensors:
      # Additional informations for Fritz!Dect devices ###############################
      bathroom_current_power: 
        value_template: "{{ state_attr('switch.bathroom', 'current_power_w') | float | default(0) }}"
        unit_of_measurement: Watt
      bathroom_temperature:
        value_template: "{{ state_attr('switch.bathroom', 'temperature') | float | default(0) }}"
        unit_of_measurement: 째C
      cookerhood_current_power: 
        value_template: "{{ state_attr('switch.cookerhood', 'current_power_w') | float | default(0) }}"
        unit_of_measurement: Watt
      cookerhood_temperature: 
        value_template: "{{ state_attr('switch.cookerhood', 'temperature') | float | default(0) }}"
        unit_of_measurement: 째C
      heatingroom_power: 
        value_template: "{{ state_attr('switch.heatingroom', 'current_power_w') | float | default(0) }}"
        unit_of_measurement: Watt
      heatingroom_temperature: 
        value_template: "{{ state_attr('switch.heatingroom', 'temperature') | float | default(0) }}"
        unit_of_measurement: 째C
      kitchen_temperature: 
        value_template: "{{ state_attr('switch.kitchenlight', 'temperature') | float | default(0) }}"
        unit_of_measurement: 째C
      livingroom_current_power: 
        value_template: "{{ state_attr('switch.livingroom', 'current_power_w') | float | default(0) }}"
        unit_of_measurement: Watt